# Generated by Django 5.2.1 on 2025-05-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='box_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_shipped',
        ),
    ]
